# Site
repository: rebeccacombs/rebeccacombs.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rebecca Combs
title: Duke/DKU CS Major
email: rdc47@duke.edu 

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  rebeccacombs
linkedin_username: rebecca-dcombs

additional_links:
- title: Stack Overflow
  icon: fab fa-stack-overflow
  url: https://stackoverflow.com/users/15087114/rdc

- title: One Page CV
  icon: far fa-file-alt
  url: https://drive.google.com/file/d/1sGDxkp75IdaUGiIQjRnEE3mlxf4dIIZf/view?usp=sharing

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Seeking hands-on experience with various tools and programming languages in the field of software development ideally, work closely with managers and mentors to evaluate requirements, estimate costs, as well as create and implement features and services. Looking to fill program manager and software engineer roles.   

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Duke University 
        caption: 2021 - Present
        sub_title: "Cumulative GPA 3.9/4.0"
        quote: Durham, North Carolina 
        description: | # this will include new lines to allow paragraphs
          *Completed courses*: Data Structures and Algorithms in Java, Intro to Data Science, Intro to Computer Systems, Discrete Mathmatics for Computer Science. 
      
      - layout: left
        title: The Winsor School
        caption: 2019 - 2021
        sub_title: "Cumulative GPA 3.9/4.0"
        quote: >
          Boston, Massachusetts 
        description: | # this will include new lines to allow paragraphs
          *Completed courses*: Introduction to Engineering and Design I, II, and Object Oriented Programming in C#.

      - layout: left
        title: Belmont High School
        caption: 2017 - 2019
        sub_title: "Cumulative GPA 4.0/4.0"
        quote: >
         Belmont, Massachusetts

  - title: Computer Science Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Luca Pinello Lab
        link: https://main.pinellolab.partners.org/
        link_text: pinellolab.org
        sub_title: Data Science Intern
        caption: June 2020 - Present
        quote: >
           Massachusetts General Hospital (MGH) Cancer Center, Harvard Medical School 
        description: | # this will include new lines to allow paragraphs
            Applied python (pandas) in Jupyter Notebooks, for STREAM analysis of hematopoietic scRNA-seq data. Prepared dataset uploaded to [singlecellvr.com](https://singlecellvr.pinellolab.partners.org/) 'kowalczyk2015-stream"' in GitHub. 
            Developed [notebook](https://github.com/rebeccacombs/velocity_preprocessing/blob/main/velocity_preprocessing.ipynb) for RNA-velocity data preparation/configuration on singlecellvr.com (can be viewed [here](https://github.com/pinellolab/singlecellvr/blob/master/supp_notebooks/ipynb_files/Supplementary_Notebook_4.ipynb) on the singlecellvr repository). 
            
            [Publication](https://www.frontiersin.org/articles/10.3389/fgene.2021.764170/full): <i>Stein, D., Chen, H., Vinyard, M., Qin, Q., Combs, R.D., Zhang, Q., Pinello, L.</i> SinglecellVR: interactive visualization of single-cell data in virtual reality ([Frontiers in Genetics](https://www.frontiersin.org/journals/genetics)).
            <br>
            <details> 
            <summary><font size="3"><mark> ↓ Kowalczyk Dataset Findings</mark></font></summary>
            <br>
            <font size="3">Click <a href="/images/pinelloLabPoster.png" target="_blank">here</a> for full-sized image.</font>
            <img src="/images/PinelloLabPoster.jpg" alt="kowalczykDatasetFindings">
            
            </details> 

      - layout: left
        title: Nancy Kanwisher Lab
        link: https://mcgovern.mit.edu/profile/nancy-kanwisher/
        link_text: kanwisherlab.org
        sub_title: Summer Intern
        caption: May 2018 - August 2018
        quote: >
           Picower Institute for Learning and Memory, Massachusetts Institute of Technology (MIT) 
        description: | # this will include new lines to allow paragraphs
            Applied HTML and python graphical user interfaces (GUIs) to develop digital oscillator. Web based app can be used for [human memory color analysis](https://en.wikipedia.org/wiki/Memory_color_effect).  
            <details> 
            <summary><font size="3"><mark> ↓ Oscillator Application</mark></font></summary>
            <video width="500" height="375" autoplay muted>
            <source src="content/americanFlagOscillator.mp4" type="video/mp4">
            Your browser does not support the video tag.
            </video>
            
            </details> 

  - title: Biology Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Biogen
        link: https://www.biogen.com/en_us/community-lab.html
        link_text: biogencommunitylab.com
        sub_title: Wet-lab biologist
        caption: June 2018
        quote: >
           Cambridge, Massachusetts
        description: | # this will include new lines to allow paragraphs
            Applied [PCR](https://en.wikipedia.org/wiki/Polymerase_chain_reaction) to [A.victoria jellyfish](https://en.wikipedia.org/wiki/Aequorea_victoria) blue fluorescent protein ([BFP](https://www.nature.com/articles/nbt1264)) cDNA for site-directed mutagenesis (Y66H). Modification turned BFP to green fluorescent protein ([GFP](https://en.wikipedia.org/wiki/Green_fluorescent_protein)). Performed bacteria transformation, gel electrophoresis ([agarose](https://en.wikipedia.org/wiki/Agarose_gel_electrophoresis) and [PAGE](https://en.wikipedia.org/wiki/Polyacrylamide_gel_electrophoresis)), [chemiluminescence](https://en.wikipedia.org/wiki/Chemiluminescence), and [spectrophotometry](https://en.wikipedia.org/wiki/Spectrophotometry). Used for cell visualization. 
            
            Lab Director: [Dr. Alazar Ayele](https://www.linkedin.com/in/alazar-ayele-10627952)
            <br>
            <details> 
            <summary><font size="3"><mark> ↓ Findings and Images</mark></font></summary>
            <br>
            <font size="3">Click <a href="/images/biogenPoster.png" target="_blank">here</a> for full-sized poster image.</font>
            <br> 
            <img src="/images/biogenPoster.png" width="420">
            <img src="/images/front.png" width="420">
            <img src="/images/labWork.png" width="420">
            <img src="/images/moreLabWork.png" width="420">
            </details>          
 
      - layout: left
        title: BioBuilder Biology Research Epicenter
        link: https://biobuilder.org/
        link_text: biobuilder.org
        sub_title: Wet-lab biologist
        caption: February 2020
        quote: >
           Cambridge, Massachusetts
        description: | # this will include new lines to allow paragraphs
            Applied PCR to [S.cerevisiae yeast DNA](https://en.wikipedia.org/wiki/Saccharomyces_cerevisiae). Identified colonies with β-carotene producing gene ([crtYB](https://pubmed.ncbi.nlm.nih.gov/24486200/)). Applied restriction digest and gel electrophoresis. Used to identify yeast culture that fortifies bread with Vitamin A. 
            
            Lab Director: [Dr. Vivek Bajaj](https://biobuilder.org/member/vivek-bajaj-learning-lab-teaching-fellow/)
            <br>
            <details> 
            <summary><font size="3"><mark> ↓ Presentation for Procedure/Findings</mark></font></summary>
            <br>
            <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQxyVjDDw-voGULE0tvquQTzHau_wtrzl35fMpbC0q6zldMWi_sNnYEMvUTOiCob_9w2bqkrU-_SVOi/embed?start=false&loop=false&delayms=3000" frameborder="0" width="850" height="515" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
            </details> 

  - title: Community Service # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: MIT Museum
        link: https://mitmuseum.mit.edu/
        link_text: mitmuseum.mit.edu
        sub_title: Teen Programming Council Member
        caption: September 2017 - May 2019 
        quote: >
           Cambridge, Massachusetts
        description: | # this will include new lines to allow paragraphs
            Organized symposia (Science Cafés) for Boston area teens. Played a key role in contacting local researchers to present their work. Delivered opening remarks at each event.
            <br>
            <details> 
            <summary><font size="3"><mark> ↓ Some Prevous Events</mark></font></summary>
            <br>
            <ul>
            <li><font size="3"><a href="https://mitmuseum.mit.edu/program/mindful-matters-teen-science-caf%C3%A9" target="_blank">Mindful Matters</a></font></li>
            <li><font size="3"><a href="https://mitmuseum.mit.edu/program/teen-science-caf%C3%A9-biotech-me-and-my-genes" target="_blank">Biotech: Me and My Genes</a></font></li>
            <li><font size="3"><a href="https://mitmuseum.mit.edu/program/teen-science-caf%C3%A9-sound-and-music" target="_blank">Sound Ideas</a></font></li>
            </ul>
            </details> 

  - title: Leadership Positions
    layout: list
    content:
      - layout: top-middle
        title: "FIRST Robotics Competition Club Team #6731"
        sub_title: Team Captain
        caption: September 2019 - May 2020
        description: |
          <br> 
          Appointed co-captain of Belmont MA's robotics team, Record Robotics. From 2017-2021, worked with teammates and mentors to compete at the annual [FIRST Robotics Competition](https://www.firstinspires.org/robotics/frc), developed and managed our [web-page](http://recordrobotics.org/) and organized outreach events at local elementary schools, the public library, and the MIT Museum. Pitched before Nobel Laureate [Sir James Fraser Stoddart](https://en.wikipedia.org/wiki/Fraser_Stoddart) to solicit financial support for the coming robotics season, leading to a $10,000 donation.
           <details> 
           <summary><font size="3"><mark> ↓ Slideshow</mark></font></summary> 
           <br> 
           <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQeHKbyMLexKHSvoGGCsZ_mJIMsUXamge9zPS3pfC42vD_LwTE5Si3X7hFTjKPeqGYo-VE3vWo6ne3T/embed?start=false&loop=false&delayms=3000"
           frameborder="0" width="560" height="350" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
           </details>

  
      - layout: top-middle
        title: "MIT Museum"
        sub_title: Teen Programming Council Member
        caption: 2017 - 2019 
  
  - title: Computer Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      Python, Java, C#, HTML, CSS, Next.js, React, R, Git, Bash, SHELL, Linux, Flask, STREAM, LaTeX, Jupyter Notebooks, Excel/Google Sheets. 

  - title: Academic and Professional Honors
    layout: text
    content: | # this will include new lines to allow paragraphs
      <ul> 
      <li><font size="3"><a href="https://www2.stat.duke.edu/datafest/winners.html">Best Visualization Award</a> at Duke DataFest (Apr 2022); view project at <a href="https://www.fishswish.net/">fishswish.net</a></font></li>
      <li><font size="3">Reviewer (ad hoc) for <a href="https://en.wikipedia.org/wiki/Briefings_in_Bioinformatics">Briefings in Bioinformatics</a> (Oxford University Press)</font></li>
      <li><font size="3"><a href="https://devpost.com/software/vivlio">HackDuke2021</a> participant</font></li>
      <li><font size="3">Top 1% PSAT, US College Board</font></li>
      <li><font size="3">District Event Finalist, <a href="https://www.thebluealliance.com/team/6731/2020">NE Regional FIRST Robotics Competition</a></font></li>
      <li><font size="3">Xerox Creativity Award, <a href="https://www.thebluealliance.com/team/6731/2020">NE Regional FIRST Robotics Competition</a></font></li>
      <li><font size="3">Honorable Mention, <a href="https://ncwit.org/">NCWIT Award for Inspirations in Computing</a></font></li>
      <li><font size="3">Old Girls Association Literary Prize, <a href="https://www.ecs.qc.ca/">Miss Edgar's & Cramp's School for Girls</a></font></li>
      </ul> 

  - title: Hobbies
    layout: text
    content: | # this will include new lines to allow paragraphs
      <ul> 
      <li><font size="3">Ballet (<a href="https://placedesarts.com/en">Place Des Artes</a>, Montreal CA)</font></li>
      <li><font size="3">Music (Belmont High School Women's Chorale, guitar, piano)</font></li> 
      <li><font size="3">Sailing (<a href="images/winsorSailing.jpg">Winsor Varsity Team</a>, Belmont High School Varsity Team, <a href="https://youtu.be/qJYHLgyvJc4">Community Boating Inc</a>)</font></li>
      </ul> 

# Footer
footer_show_references: true
references_title: made with jekyll - All Rights Reserved.

# Build settings
#theme: modern-resume-theme 
remote_theme: sproogen/modern-resume-theme 

sass:
  sass_dir: _sass\\
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
