# Site
repository: rebeccacombs/rebeccacombs.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rebecca Combs
title: Duke CS Major  
email: rdc47@duke.edu
# website: www.github.com/rebeccacombs/rebeccacombs.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username:  rebeccacombs
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
#facebook_username: Rebecca Combs
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: rebecca-combs-b347211b5
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: linedin
  #icon: linkedin_username
  #url: https://linkedin.com/in/rebecca-combs-b347211b5
#- title: facebook
  #icon: facebook_username
 # url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Duke Universtiy undergraduate. Computer science and biology researcher. Community volunteer. Amateur sailor and musician.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Winsor School
        caption: 2019 - 2021
                 All girls' private school located on 103 Pilgrim Road, Boston, Massachusetts.
        sub_title: "Cumulative GPA 3.9/4.0"
        quote: >
          All girls' private school located on 103 Pilgrim Road, Boston, Massachusetts. 
        description: | # this will include new lines to allow paragraphs
          Completed courses: Introduction to Engineering and Design I, II, and Object Oriented Programming in C#.
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Belmont High School
        caption: 2017 - 2019
                 All girls' private school located on 103 Pilgrim Road, Boston, Massachusetts.
        sub_title: "Cumulative GPA 4.0/4.0"
        quote: >
          Co-ed public high school located on 221 Concord Avenue, Belmont, Massachusetts.  

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
